(() => {
  const TERRAIN_NAMES={lowland:'Lowlands',highland:'Highlands',river_valley:'River Valley',coastal:'Coastal',sea:'Sea',swamp:'Swamp'};
  const FEATURE_ICONS={village:'⌂',fortress:'♜',city:'♛',capital:'★'};
  const state={campaign:null,user:null,hexes:[],selected:null,scale:.86,x:0,y:0,dragging:false,dragStart:null};

  function loadStyles(){if(document.querySelector('link[data-me-style]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='dev_mighty_empires.css?v=1';l.dataset.meStyle='1';document.head.appendChild(l);}
  function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
  function isOwner(){return state.campaign&&state.user&&state.campaign.owner_id===state.user.id;}

  async function getUser(){const {data,error}=await window.whrSupabase.auth.getUser();if(error)throw error;return data?.user||null;}
  async function getCampaign(id){const {data,error}=await window.whrSupabase.from('campaigns').select('id,campaign_type_id,owner_id,name,description,visibility,created_at,updated_at').eq('id',id).single();if(error)throw error;return data;}
  async function loadHexes(){const {data,error}=await window.whrSupabase.from('mighty_empire_hexes').select('id,campaign_id,q,r,terrain_type,terrain_variant,rotation,settlement_type,owner_id,razed,under_siege,special_state,updated_at').eq('campaign_id',state.campaign.id).order('q').order('r');if(error)throw error;state.hexes=data||[];}

  function ensureDialog(){let d=document.getElementById('mightyEmpiresCampaignDialog');if(d)return d;d=document.createElement('dialog');d.id='mightyEmpiresCampaignDialog';d.className='me-dialog';d.innerHTML=`<div class="me-shell"><header class="me-header"><div><div class="eyebrow">Mighty Empires</div><h2 id="meCampaignName">Campaign</h2><p id="meCampaignMeta">Persistent hex campaign</p></div><div class="me-header-actions"><button id="meReload" class="me-btn secondary" type="button">Reload Map</button><button id="meClose" class="me-btn secondary" type="button">Close</button></div></header><div id="meBody" class="me-layout"></div></div>`;document.body.appendChild(d);d.querySelector('#meClose').onclick=()=>d.close();d.querySelector('#meReload').onclick=async()=>{await loadHexes();render();};return d;}

  function seeded(q,r){let n=(q*374761393+r*668265263+state.campaign.id.charCodeAt(0)*1274126177)>>>0;n=(n^(n>>13))*1274126177;n=(n^(n>>16))>>>0;return n/4294967295;}
  function terrainFor(q,r,cols,rows){const edge=Math.min(q,r,cols-1-q,rows-1-r);const a=seeded(q,r);if(edge===0&&a<.5)return 'sea';if(edge<=1&&a<.28)return 'coastal';if(a<.16)return 'highland';if(a<.25)return 'river_valley';if(a<.30)return 'swamp';return 'lowland';}
  function buildHexRows(size){const dims={small:[7,7],medium:[9,9],large:[11,11]};const [cols,rows]=dims[size]||dims.medium;const out=[];for(let q=0;q<cols;q++){for(let r=0;r<rows;r++){out.push({campaign_id:state.campaign.id,q,r,terrain_type:terrainFor(q,r,cols,rows),terrain_variant:'prototype',rotation:[0,60,120,180,240,300][Math.floor(seeded(r,q)*6)],settlement_type:(q===Math.floor(cols/2)&&r===Math.floor(rows/2))?'capital':null,owner_id:(q===Math.floor(cols/2)&&r===Math.floor(rows/2))?state.user.id:null,special_state:{map_size:size}});}}return out;}

  async function generateMap(size,button){button.disabled=true;button.textContent='Generating…';try{const rows=buildHexRows(size);const {error}=await window.whrSupabase.from('mighty_empire_hexes').insert(rows);if(error)throw error;await loadHexes();render();}catch(err){showError(err.message||String(err));button.disabled=false;button.textContent='Generate Map';}}
  function showError(msg){const body=document.getElementById('meBody');if(body)body.innerHTML=`<div class="me-setup"><h3>Unable to load Mighty Empires</h3><div class="me-error">${esc(msg)}</div><p>If the error mentions a missing table, run <strong>supabase/013_mighty_empires.sql</strong> against the Dev Supabase project.</p></div>`;}

  function renderSetup(){const body=document.getElementById('meBody');body.innerHTML=`<section class="me-setup"><div class="eyebrow">Campaign Map</div><h3>Create the realm</h3><p>This campaign does not have a map yet. Generate the first persistent hex map. The hexes will be stored in Supabase and everyone in this campaign will see the same map.</p>${isOwner()?`<div class="me-setup-grid"><label>Map size<select id="meMapSize"><option value="small">Small — 7 × 7</option><option value="medium" selected>Medium — 9 × 9</option><option value="large">Large — 11 × 11</option></select></label></div><button id="meGenerate" class="me-btn" type="button">Generate Map</button><div class="me-status">Terrain is deliberately provisional while we build the painted tile library and intelligent terrain connections.</div>`:`<div class="me-empty">The campaign owner needs to generate the map first.</div>`}</section>`;body.className='me-layout';document.getElementById('meGenerate')?.addEventListener('click',e=>generateMap(document.getElementById('meMapSize').value,e.currentTarget));}

  function mapBounds(){let maxQ=0,maxR=0;state.hexes.forEach(h=>{maxQ=Math.max(maxQ,h.q);maxR=Math.max(maxR,h.r);});return{cols:maxQ+1,rows:maxR+1};}
  function applyTransform(){const map=document.getElementById('meMap');if(map)map.style.transform=`translate(${state.x}px,${state.y}px) scale(${state.scale}) translate(-50%,-50%)`;}
  function resetView(){state.scale=.86;state.x=0;state.y=0;applyTransform();}
  function zoom(d){state.scale=Math.max(.45,Math.min(1.8,state.scale+d));applyTransform();}

  function renderMap(){const map=document.getElementById('meMap');if(!map)return;map.innerHTML='';const w=90,h=104,xStep=w*.75;state.hexes.forEach(hex=>{const b=document.createElement('button');b.type='button';b.className=`me-hex ${hex.terrain_type}${state.selected?.id===hex.id?' selected':''}`;b.style.left=`${hex.q*xStep}px`;b.style.top=`${hex.r*h+(hex.q%2?h/2:0)}px`;b.dataset.hexId=hex.id;b.innerHTML=`<span class="me-hex-label">${hex.q},${hex.r}</span>${hex.settlement_type&&FEATURE_ICONS[hex.settlement_type]?`<span class="me-feature" title="${esc(hex.settlement_type)}">${FEATURE_ICONS[hex.settlement_type]}</span>`:''}`;b.onclick=e=>{e.stopPropagation();state.selected=hex;renderMap();renderDetails();};map.appendChild(b);});applyTransform();}

  function renderDetails(){const side=document.getElementById('meSidebar');if(!side)return;if(!state.selected){side.innerHTML='<div class="eyebrow">Selected Hex</div><div class="me-empty">Select a hex to inspect it.</div>';return;}const h=state.selected;side.innerHTML=`<div class="eyebrow">Selected Hex</div><h3>Hex ${h.q}, ${h.r}</h3><dl><dt>Terrain</dt><dd>${esc(TERRAIN_NAMES[h.terrain_type]||h.terrain_type)}</dd><dt>Feature</dt><dd>${esc(h.settlement_type||'None')}</dd><dt>Owner</dt><dd>${h.owner_id?esc(h.owner_id===state.user.id?'You':'Campaign player'):'Unclaimed'}</dd><dt>Siege</dt><dd>${h.under_siege?'Yes':'No'}</dd><dt>RazEd</dt><dd>${h.razed?'Yes':'No'}</dd></dl>${isOwner()?`<div class="me-editor"><label>Terrain<select id="meTerrain">${Object.keys(TERRAIN_NAMES).map(t=>`<option value="${t}" ${t===h.terrain_type?'selected':''}>${TERRAIN_NAMES[t]}</option>`).join('')}</select></label><label>Settlement<select id="meSettlement"><option value="">None</option>${['barren','village','fortress','city','capital'].map(t=>`<option value="${t}" ${t===h.settlement_type?'selected':''}>${t[0].toUpperCase()+t.slice(1)}</option>`).join('')}</select></label><button id="meSaveHex" class="me-btn" type="button">Save Hex</button><div id="meSaveStatus" class="me-status"></div></div>`:''}`;document.getElementById('meSaveHex')?.addEventListener('click',saveSelectedHex);}

  async function saveSelectedHex(){const btn=document.getElementById('meSaveHex'),status=document.getElementById('meSaveStatus');btn.disabled=true;status.textContent='Saving…';const terrain=document.getElementById('meTerrain').value;const settlement=document.getElementById('meSettlement').value||null;const {data,error}=await window.whrSupabase.from('mighty_empire_hexes').update({terrain_type:terrain,settlement_type:settlement,updated_at:new Date().toISOString()}).eq('id',state.selected.id).select().single();if(error){status.textContent=error.message;btn.disabled=false;return;}state.selected=data;const i=state.hexes.findIndex(h=>h.id===data.id);if(i>=0)state.hexes[i]=data;renderMap();renderDetails();}

  function wireMap(){const wrap=document.getElementById('meMapWrap');document.getElementById('meZoomIn').onclick=()=>zoom(.12);document.getElementById('meZoomOut').onclick=()=>zoom(-.12);document.getElementById('meReset').onclick=resetView;wrap.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?.08:-.08);},{passive:false});wrap.addEventListener('pointerdown',e=>{if(e.target.closest('.me-hex'))return;state.dragging=true;state.dragStart={x:e.clientX,y:e.clientY,ox:state.x,oy:state.y};wrap.classList.add('dragging');wrap.setPointerCapture(e.pointerId);});wrap.addEventListener('pointermove',e=>{if(!state.dragging)return;state.x=state.dragStart.ox+(e.clientX-state.dragStart.x);state.y=state.dragStart.oy+(e.clientY-state.dragStart.y);applyTransform();});wrap.addEventListener('pointerup',()=>{state.dragging=false;wrap.classList.remove('dragging');});}

  function render(){document.getElementById('meCampaignName').textContent=state.campaign.name;document.getElementById('meCampaignMeta').textContent=`${state.hexes.length?state.hexes.length+' hexes':'Map not generated'} · ${isOwner()?'Campaign owner':'Campaign member'}`;if(!state.hexes.length){renderSetup();return;}const body=document.getElementById('meBody');body.className='me-layout';body.innerHTML=`<div id="meMapWrap" class="me-map-wrap"><div id="meMap" class="me-map"></div><div class="me-map-controls"><button id="meZoomIn" type="button">+</button><button id="meZoomOut" type="button">−</button><button id="meReset" type="button">⌂</button></div></div><aside id="meSidebar" class="me-sidebar"></aside>`;state.selected=null;wireMap();renderMap();renderDetails();requestAnimationFrame(resetView);}

  async function openMightyEmpires(id){loadStyles();try{if(!window.whrSupabase)throw new Error('Supabase is not ready. Please refresh the page.');state.user=await getUser();if(!state.user)throw new Error('You must be signed in to open a campaign.');state.campaign=await getCampaign(id);if(state.campaign.campaign_type_id!=='mighty_empires')return false;await loadHexes();document.getElementById('campaignHubDialog')?.close();const d=ensureDialog();render();d.showModal();return true;}catch(err){const d=ensureDialog();d.showModal();showError(err.message||String(err));return true;}}

  document.addEventListener('click',e=>{const btn=e.target.closest?.('[data-open-campaign]');if(!btn)return;const id=btn.dataset.openCampaign;if(!id)return;e.preventDefault();e.stopImmediatePropagation();openMightyEmpires(id).then(handled=>{if(!handled){btn.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));}});},true);

  loadStyles();window.whrOpenMightyEmpires=openMightyEmpires;
})();
