(() => {
  const TYPE='thorskins_island';
  const POINTS=1500;
  let campaignId=null;
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');

  function installStyles(){if(document.getElementById('thorskinsStyles'))return;const s=document.createElement('style');s.id='thorskinsStyles';s.textContent=`.thorskins-teams{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.thorskins-team{border:1px solid #d8dee5;border-radius:7px;padding:12px;background:#fff}.thorskins-team-head{display:flex;gap:8px;align-items:center}.thorskins-team-head input{min-width:0;flex:1}.thorskins-player{padding:8px 0;border-top:1px solid #edf0f2}.thorskins-player:first-child{border-top:0}.thorskins-hidden{color:#7a8188;font-style:italic}@media(max-width:720px){.thorskins-teams{grid-template-columns:1fr}}`;document.head.appendChild(s);}

  async function user(){const {data}=await window.whrSupabase.auth.getUser();return data?.user||null;}
  async function campaign(id){const {data,error}=await window.whrSupabase.from('campaigns').select('id,name,owner_id,campaign_type_id').eq('id',id).single();if(error)throw error;return data;}
  async function members(id){const {data,error}=await window.whrSupabase.from('campaign_members').select('campaign_id,user_id,role,team_id,joined_at').eq('campaign_id',id).order('joined_at');if(error)throw error;return data||[];}
  async function teams(id){const {data,error}=await window.whrSupabase.from('campaign_teams').select('id,campaign_id,name').eq('campaign_id',id).order('created_at');if(error)throw error;return data||[];}
  async function profiles(ids){if(!ids.length)return new Map();const {data}=await window.whrSupabase.from('profiles').select('id,display_name').in('id',[...new Set(ids)]);return new Map((data||[]).map(p=>[p.id,p.display_name]));}

  async function ensureTeams(c,u,ts){if(c.owner_id===u.id&&ts.length===0){const {error}=await window.whrSupabase.rpc('whr_thorskins_initialise_teams',{p_campaign_id:c.id});if(error)throw error;return teams(c.id);}return ts;}

  async function render(){const content=document.getElementById('campaignFormContent');if(!content||!campaignId)return;try{const [c,u]=await Promise.all([campaign(campaignId),user()]);if(!u||c.campaign_type_id!==TYPE)return;let [ms,ts]=await Promise.all([members(c.id),teams(c.id)]);ts=await ensureTeams(c,u,ts);const names=await profiles(ms.map(m=>m.user_id));const players=ms.filter(m=>m.role==='member'&&m.user_id!==c.owner_id);const isOwner=u.id===c.owner_id;const mine=ms.find(m=>m.user_id===u.id);const panel=document.createElement('section');panel.className='campaign-subpanel';panel.dataset.thorskinsPanel=c.id;panel.innerHTML=`<h3>Thorskins Island Teams</h3><div class="campaign-meta">Campaign Master + 8 competing players · four teams of two · standard ${POINTS} point armies · army lists are visible only to the Campaign Master, their owner and that player's team-mate.</div><div class="campaign-meta" style="margin-top:5px"><strong>Players:</strong> ${players.length} / 8${isOwner?' · You are Campaign Master and do not occupy a player slot.':''}</div><div class="thorskins-teams">${ts.map(t=>{const tm=players.filter(p=>p.team_id===t.id);return `<div class="thorskins-team"><div class="thorskins-team-head"><input value="${esc(t.name)}" maxlength="50" data-team-name="${esc(t.id)}"><button class="campaign-button secondary" data-save-team="${esc(t.id)}">Name Team</button></div><div>${tm.length?tm.map(p=>`<div class="thorskins-player"><strong>${esc(names.get(p.user_id)||'WHR Player')}</strong>${p.user_id===u.id?' · You':''}</div>`).join(''):'<div class="campaign-meta" style="padding-top:8px">No players assigned</div>'}</div></div>`}).join('')}</div>${isOwner?`<div style="margin-top:14px"><h3>Assign Players</h3>${players.map(p=>`<div class="campaign-person-row"><div><strong>${esc(names.get(p.user_id)||'WHR Player')}</strong></div><select data-assign-player="${esc(p.user_id)}"><option value="">Unassigned</option>${ts.map(t=>`<option value="${esc(t.id)}" ${p.team_id===t.id?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div>`).join('')}</div>`:''}`;
      content.querySelector('[data-thorskins-panel]')?.remove();content.prepend(panel);
      panel.querySelectorAll('[data-save-team]').forEach(b=>b.onclick=async()=>{const input=panel.querySelector(`[data-team-name="${CSS.escape(b.dataset.saveTeam)}"]`);const name=input.value.trim();if(name.length<2)return alert('Team name must be at least 2 characters.');const {error}=await window.whrSupabase.from('campaign_teams').update({name,updated_at:new Date().toISOString()}).eq('id',b.dataset.saveTeam);if(error)return alert(error.message);showToast('Team name saved');render();});
      panel.querySelectorAll('[data-assign-player]').forEach(sel=>sel.onchange=async()=>{if(!sel.value)return;const {error}=await window.whrSupabase.rpc('whr_thorskins_assign_team',{p_campaign_id:c.id,p_user_id:sel.dataset.assignPlayer,p_team_id:sel.value});if(error){alert(error.message);return render();}showToast('Team assignment saved');render();});
    }catch(e){console.error('Thorskins Island setup failed',e);if(/campaign_teams|whr_thorskins/i.test(e?.message||'')){const content=document.getElementById('campaignFormContent');if(content&&!content.querySelector('[data-thorskins-panel]')){const p=document.createElement('section');p.className='campaign-subpanel';p.dataset.thorskinsPanel=campaignId;p.innerHTML='<h3>Thorskins Island Teams</h3><div class="campaign-message">Database setup required: run supabase/014_thorskins_island_teams.sql in the DEV Supabase project.</div>';content.prepend(p);}}}
  }

  window.addEventListener('click',e=>{const open=e.target.closest?.('[data-open-campaign]');if(open?.dataset.openCampaign){campaignId=open.dataset.openCampaign;setTimeout(render,120);setTimeout(render,400);}},true);
  new MutationObserver(()=>{const d=document.getElementById('campaignFormDialog');if(d?.open&&campaignId&&!document.querySelector(`[data-thorskins-panel="${CSS.escape(campaignId)}"]`))setTimeout(render,0);}).observe(document.body,{childList:true,subtree:true});
  installStyles();
})();
