// Mighty Empires manual map builder prototype (Dev only)
(() => {
  const GRID_COLS=9, GRID_ROWS=9, W=104, H=90, XSTEP=78;
  const ASSETS=[
    {id:'coastal-01',name:'Coastal 01',terrain:'coastal',src:'assets/mighty-empires/tiles/coastal/coastal-01.webp',limit:1},
    {id:'highland-01',name:'Highland 01',terrain:'highland',src:'assets/mighty-empires/tiles/highland/highland-01.webp',limit:1},
    {id:'lowland-01',name:'Lowland 01',terrain:'lowland',src:'assets/mighty-empires/tiles/lowland/lowland-01.webp',limit:1},
    {id:'river-01',name:'River Valley 01',terrain:'river_valley',src:'assets/mighty-empires/tiles/river-valley/river-01.webp',limit:1},
    {id:'sea-01',name:'Sea',terrain:'sea',src:'assets/mighty-empires/tiles/sea/sea-01.webp',limit:28,rotatable:false}
  ];
  const byAsset=new Map(ASSETS.map(a=>[a.id,a]));
  const state={campaign:null,user:null,rows:[],selectedAsset:null,selectedHex:null,movingId:null,busy:false};

  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const key=(q,r)=>`${q},${r}`;
  const isOwner=()=>state.campaign&&state.user&&state.campaign.owner_id===state.user.id;

  function styles(){
    if(document.getElementById('meManualStyles'))return;
    const s=document.createElement('style');s.id='meManualStyles';s.textContent=`
      .meb-dialog{width:min(1460px,98vw);height:min(920px,94vh);border:0;border-radius:12px;padding:0;box-shadow:0 22px 70px rgba(0,0,0,.38)}
      .meb-dialog::backdrop{background:rgba(0,0,0,.62)} .meb-shell{height:100%;display:flex;flex-direction:column;background:#f4f1e8}
      .meb-header{display:flex;justify-content:space-between;gap:16px;align-items:center;background:#0d1d12;color:white;padding:16px 20px;border-bottom:3px solid #7b211b}
      .meb-header h2{margin:2px 0 0;color:white}.meb-header p{margin:4px 0 0;color:#d8e0da}.meb-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
      .meb-btn{border:1px solid #aeb7af;background:white;color:#263027;border-radius:6px;padding:9px 12px;font-weight:800;cursor:pointer}.meb-btn.primary{background:#8f261e;border-color:#8f261e;color:white}.meb-btn:disabled{opacity:.45;cursor:not-allowed}
      .meb-body{flex:1;min-height:0;display:grid;grid-template-columns:260px 1fr 290px}.meb-tray,.meb-inspector{background:#fff;padding:16px;overflow:auto}.meb-tray{border-right:1px solid #d9ddd8}.meb-inspector{border-left:1px solid #d9ddd8}
      .meb-tray h3,.meb-inspector h3{margin:2px 0 12px}.meb-help{font-size:13px;color:#606963;line-height:1.4;margin-bottom:14px}
      .meb-assets{display:grid;grid-template-columns:1fr 1fr;gap:10px}.meb-asset{border:2px solid transparent;border-radius:8px;background:#f5f5f2;padding:7px;cursor:pointer;text-align:left}.meb-asset.selected{border-color:#8f261e;background:#fff6f3}.meb-asset:disabled{opacity:.45;cursor:not-allowed}.meb-asset img{width:100%;aspect-ratio:104/90;object-fit:contain;display:block}.meb-asset strong{display:block;font-size:11px;margin-top:5px}.meb-asset small{font-size:10px;color:#68716b}
      .meb-workspace{position:relative;overflow:auto;background:#b8cdd1;background-image:radial-gradient(rgba(255,255,255,.28) 1px,transparent 1px);background-size:18px 18px}.meb-canvas{position:relative;width:${(GRID_COLS-1)*XSTEP+W+60}px;height:${GRID_ROWS*H+45+60}px;margin:28px auto}
      .meb-slot{position:absolute;width:${W}px;height:${H}px;padding:0;border:1px dashed rgba(43,70,61,.35);background:rgba(255,255,255,.13);clip-path:polygon(25% 0,75% 0,100% 50%,75% 100%,25% 100%,0 50%);cursor:pointer}.meb-slot:hover{background:rgba(255,255,255,.28)}.meb-slot.occupied{border:0;background:transparent}.meb-slot.active{outline:3px solid #8f261e;outline-offset:2px}.meb-slot img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;transform-origin:50% 50%;pointer-events:none}.meb-coord{position:absolute;inset:auto 0 6px;text-align:center;font-size:9px;color:rgba(0,0,0,.48);pointer-events:none}.meb-slot.occupied .meb-coord{display:none}
      .meb-empty{padding:28px 16px;color:#64706a;text-align:center}.meb-warning{margin:16px;padding:16px;border:1px solid #d7b564;background:#fff6d8;border-radius:8px;color:#5d4914}.meb-inspector-preview{width:180px;max-width:100%;display:block;margin:8px auto 16px}.meb-inspector dl{display:grid;grid-template-columns:90px 1fr;gap:8px;margin:14px 0}.meb-inspector dt{font-weight:800}.meb-inspector dd{margin:0}.meb-inspector-actions{display:grid;gap:8px}.meb-status{margin-top:14px;font-size:12px;color:#67716b}
      @media(max-width:850px){.meb-dialog{width:100vw;height:100vh;max-width:none;max-height:none;border-radius:0}.meb-header{align-items:flex-start}.meb-body{grid-template-columns:1fr;grid-template-rows:auto minmax(420px,1fr) auto}.meb-tray{border-right:0;border-bottom:1px solid #d9ddd8;max-height:225px}.meb-assets{grid-template-columns:repeat(5,minmax(90px,1fr));overflow:auto}.meb-asset{min-width:90px}.meb-inspector{border-left:0;border-top:1px solid #d9ddd8;max-height:260px}.meb-actions{max-width:58%}.meb-btn{padding:8px 10px}.meb-header h2{font-size:22px}}
    `;document.head.appendChild(s);
  }

  async function getUser(){const {data,error}=await window.whrSupabase.auth.getUser();if(error)throw error;return data?.user||null;}
  async function getCampaign(id){const {data,error}=await window.whrSupabase.from('campaigns').select('id,owner_id,name,campaign_type_id').eq('id',id).single();if(error)throw error;return data;}
  async function loadRows(){const {data,error}=await window.whrSupabase.from('mighty_empire_hexes').select('id,campaign_id,q,r,terrain_type,terrain_variant,rotation,special_state').eq('campaign_id',state.campaign.id).order('q').order('r');if(error)throw error;state.rows=data||[];}
  const hasLegacy=()=>state.rows.some(r=>!byAsset.has(r.terrain_variant));

  function dialog(){let d=document.getElementById('mightyEmpiresManualDialog');if(d)return d;styles();d=document.createElement('dialog');d.id='mightyEmpiresManualDialog';d.className='meb-dialog';d.innerHTML=`<div class="meb-shell"><header class="meb-header"><div><div class="eyebrow">Mighty Empires · Manual Builder</div><h2 id="mebName">Campaign</h2><p id="mebMeta">Build the campaign map from individual tiles.</p></div><div class="meb-actions"><button id="mebClear" class="meb-btn" type="button">Clear Map</button><button id="mebReload" class="meb-btn" type="button">Reload</button><button id="mebClose" class="meb-btn" type="button">Close</button></div></header><div id="mebBody" class="meb-body"></div></div>`;document.body.appendChild(d);d.querySelector('#mebClose').onclick=()=>d.close();d.querySelector('#mebReload').onclick=reload;d.querySelector('#mebClear').onclick=clearMap;return d;}

  function usage(assetId){return state.rows.filter(r=>r.terrain_variant===assetId).length;}
  function renderTray(){const tray=document.getElementById('mebTray');if(!tray)return;tray.innerHTML=`<div class="eyebrow">Tile Tray</div><h3>Prototype tiles</h3><div class="meb-help">Select a tile, then tap an empty hex. These five standalone assets prove the new manual-map approach before we extract the full library.</div><div class="meb-assets">${ASSETS.map(a=>{const used=usage(a.id),remaining=Math.max(0,a.limit-used);return `<button class="meb-asset ${state.selectedAsset===a.id?'selected':''}" data-asset="${a.id}" type="button" ${(!isOwner()||remaining===0)?'disabled':''}><img src="${a.src}" alt="${esc(a.name)}"><strong>${esc(a.name)}</strong><small>${remaining} remaining</small></button>`}).join('')}</div><div class="meb-status">Land test tiles are limited to one each. Sea uses an inventory of 28.</div>`;tray.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{state.selectedAsset=b.dataset.asset;state.movingId=null;renderTray();renderInspector();});}

  function rowAt(q,r){return state.rows.find(x=>x.q===q&&x.r===r);}
  function renderBoard(){const board=document.getElementById('mebBoard');if(!board)return;board.innerHTML='';for(let q=0;q<GRID_COLS;q++)for(let r=0;r<GRID_ROWS;r++){const row=rowAt(q,r);const b=document.createElement('button');b.type='button';b.className=`meb-slot${row?' occupied':''}${state.selectedHex?.id===row?.id?' active':''}`;b.style.left=`${q*XSTEP+20}px`;b.style.top=`${r*H+(q%2?H/2:0)+10}px`;b.dataset.q=q;b.dataset.r=r;if(row){const a=byAsset.get(row.terrain_variant);if(a){b.innerHTML=`<img src="${a.src}" alt="${esc(a.name)}" style="transform:rotate(${Number(row.rotation)||0}deg)"><span class="meb-coord">${q},${r}</span>`;}else b.textContent='Legacy';}else b.innerHTML=`<span class="meb-coord">${q},${r}</span>`;b.onclick=()=>slotClick(q,r,row);board.appendChild(b);}}

  function renderInspector(){const p=document.getElementById('mebInspector');if(!p)return;if(state.movingId){const row=state.rows.find(r=>r.id===state.movingId),a=row&&byAsset.get(row.terrain_variant);p.innerHTML=`<div class="eyebrow">Move Tile</div><h3>${esc(a?.name||'Tile')}</h3><p class="meb-help">Tap an empty hex to move this tile there.</p><button id="mebCancelMove" class="meb-btn" type="button">Cancel Move</button>`;p.querySelector('#mebCancelMove').onclick=()=>{state.movingId=null;renderInspector();};return;}const row=state.selectedHex;if(!row){const a=byAsset.get(state.selectedAsset);p.innerHTML=a?`<div class="eyebrow">Selected Tile</div><h3>${esc(a.name)}</h3><img class="meb-inspector-preview" src="${a.src}" alt=""><p class="meb-help">Tap an empty position on the map to place it.</p>`:`<div class="eyebrow">Map Builder</div><div class="meb-empty">Choose a tile from the tray or select a placed tile.</div>`;return;}const a=byAsset.get(row.terrain_variant);p.innerHTML=`<div class="eyebrow">Placed Tile</div><h3>${esc(a?.name||row.terrain_variant)}</h3>${a?`<img class="meb-inspector-preview" src="${a.src}" alt="" style="transform:rotate(${Number(row.rotation)||0}deg)">`:''}<dl><dt>Position</dt><dd>${row.q}, ${row.r}</dd><dt>Rotation</dt><dd>${Number(row.rotation)||0}°</dd></dl>${isOwner()?`<div class="meb-inspector-actions">${a?.rotatable===false?'':`<button id="mebRotate" class="meb-btn primary" type="button">Rotate 60°</button>`}<button id="mebMove" class="meb-btn" type="button">Move Tile</button><button id="mebRemove" class="meb-btn" type="button">Remove Tile</button></div>`:''}`;p.querySelector('#mebRotate')?.addEventListener('click',rotateSelected);p.querySelector('#mebMove')?.addEventListener('click',()=>{state.movingId=row.id;renderInspector();});p.querySelector('#mebRemove')?.addEventListener('click',removeSelected);}

  async function slotClick(q,r,row){if(row){state.selectedHex=row;state.selectedAsset=null;state.movingId=null;renderBoard();renderTray();renderInspector();return;}if(!isOwner()||state.busy)return;if(state.movingId){const moving=state.rows.find(x=>x.id===state.movingId);if(!moving)return;state.busy=true;try{const {error}=await window.whrSupabase.from('mighty_empire_hexes').update({q,r,updated_at:new Date().toISOString()}).eq('id',moving.id);if(error)throw error;moving.q=q;moving.r=r;state.selectedHex=moving;state.movingId=null;renderAll();}catch(e){alert(`Unable to move tile: ${e.message||e}`);}finally{state.busy=false;}return;}const a=byAsset.get(state.selectedAsset);if(!a||usage(a.id)>=a.limit)return;state.busy=true;try{const payload={campaign_id:state.campaign.id,q,r,terrain_type:a.terrain,terrain_variant:a.id,rotation:0,settlement_type:null,owner_id:null,razed:false,under_siege:false,special_state:{manual_builder:true,tile_id:a.id},updated_at:new Date().toISOString()};const {data,error}=await window.whrSupabase.from('mighty_empire_hexes').insert(payload).select('id,campaign_id,q,r,terrain_type,terrain_variant,rotation,special_state').single();if(error)throw error;state.rows.push(data);state.selectedHex=data;state.selectedAsset=null;renderAll();}catch(e){alert(`Unable to place tile: ${e.message||e}`);}finally{state.busy=false;}}

  async function rotateSelected(){const row=state.selectedHex,a=row&&byAsset.get(row.terrain_variant);if(!row||!a||a.rotatable===false||state.busy)return;state.busy=true;try{const rotation=((Number(row.rotation)||0)+60)%360;const {error}=await window.whrSupabase.from('mighty_empire_hexes').update({rotation,updated_at:new Date().toISOString()}).eq('id',row.id);if(error)throw error;row.rotation=rotation;renderBoard();renderInspector();}catch(e){alert(`Unable to rotate tile: ${e.message||e}`);}finally{state.busy=false;}}
  async function removeSelected(){const row=state.selectedHex;if(!row||state.busy)return;if(!confirm('Remove this tile from the map?'))return;state.busy=true;try{const {error}=await window.whrSupabase.from('mighty_empire_hexes').delete().eq('id',row.id);if(error)throw error;state.rows=state.rows.filter(x=>x.id!==row.id);state.selectedHex=null;renderAll();}catch(e){alert(`Unable to remove tile: ${e.message||e}`);}finally{state.busy=false;}}
  async function clearMap(){if(!isOwner()||!state.campaign||state.busy)return;if(!confirm('Clear every Mighty Empires tile from this campaign?\n\nThis removes the old generated map too, and cannot be undone.'))return;state.busy=true;try{const {error}=await window.whrSupabase.from('mighty_empire_hexes').delete().eq('campaign_id',state.campaign.id);if(error)throw error;state.rows=[];state.selectedHex=null;state.selectedAsset=null;state.movingId=null;render();}catch(e){alert(`Unable to clear map: ${e.message||e}`);}finally{state.busy=false;}}
  async function reload(){if(!state.campaign||state.busy)return;state.busy=true;try{await loadRows();state.selectedHex=null;state.movingId=null;render();}catch(e){alert(`Unable to reload map: ${e.message||e}`);}finally{state.busy=false;}}

  function renderAll(){renderBoard();renderTray();renderInspector();document.getElementById('mebMeta').textContent=`${state.rows.length} placed tile${state.rows.length===1?'':'s'} · ${isOwner()?'Campaign owner':'Campaign player'}`;}
  function render(){const d=dialog(),body=document.getElementById('mebBody');document.getElementById('mebName').textContent=state.campaign?.name||'Mighty Empires';document.getElementById('mebClear').hidden=!isOwner();if(hasLegacy()){body.innerHTML=`<div style="grid-column:1/-1"><div class="meb-warning"><strong>Old generated map detected.</strong><p>This campaign still contains terrain from the retired automatic generator. Clear it before starting the new manual tile map.</p>${isOwner()?'<button id="mebLegacyClear" class="meb-btn primary" type="button">Clear Old Generated Map</button>':'<p>The campaign owner needs to clear the old map.</p>'}</div></div>`;document.getElementById('mebMeta').textContent=`${state.rows.length} legacy hexes · Manual builder ready`;document.getElementById('mebLegacyClear')?.addEventListener('click',clearMap);return;}body.innerHTML=`<aside id="mebTray" class="meb-tray"></aside><main class="meb-workspace"><div id="mebBoard" class="meb-canvas"></div></main><aside id="mebInspector" class="meb-inspector"></aside>`;renderAll();}

  async function openCampaign(id){try{const d=dialog();state.user=await getUser();if(!state.user)throw new Error('Sign in to open this campaign.');state.campaign=await getCampaign(id);state.rows=[];state.selectedAsset=null;state.selectedHex=null;state.movingId=null;await loadRows();render();document.getElementById('campaignHubDialog')?.close?.();if(!d.open)d.showModal();}catch(e){console.error('Mighty Empires manual builder failed',e);alert(`Unable to open Mighty Empires: ${e.message||e}`);}}

  window.whrOpenMightyEmpires=openCampaign;
  document.addEventListener('click',e=>{const b=e.target.closest?.('[data-open-campaign]');const card=b?.closest?.('.campaign-card');if(!b?.dataset?.openCampaign||!card?.textContent?.includes('Mighty Empires'))return;e.preventDefault();e.stopImmediatePropagation();openCampaign(b.dataset.openCampaign);},true);
})();
